services:
  mongo:
    image: mongo:7
    container_name: techsyslog-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INIDB_ROOT_USERNAME: root
      MONGO_INIDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: src/TechsysLog.Api/Dockerfile
    container_name: techsyslog-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      MongoDb__ConnectionString: mongodb://root:root@mongo:27017
      MongoDb__DatabaseName: techsyslog
      Jwt__Issuer: techsyslog
      Jwt__Audience: techsyslog
      Jwt__SecretKey: CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_32+
      Jwt__ExpirationMinutes: "60"
    depends_on:
      - mongo

volumes:
  mongo_data:
